- hosts: server
  become: true
  tasks:
    - name: Install Apache, MariaDB (MySQL-Ersatz) and PHP
      ansible.builtin.apt:
        name:
          - apache2
          - mariadb-server    # <--- Korrigiert (ersetzt mysql-server)
          - php-mysql         # <--- Korrigiert (generischer Name für PHP-MySQL-Anbindung)
          - php               # <--- Korrigiert (installiert die Standard-PHP-Version des Images, bei Debian 9 ist das PHP 7.0)
        state: present
        update_cache: true

    - name: Copy app to the web root
      ansible.builtin.copy:
        src: web-app/
        dest: /var/www/html/
